name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
